swagger: "2.0"
info:
  title: Workflow Manager
  version: 2.0.0
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
# securityDefinitions:
#   basicAuth:
#     type: basic
#     description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
# authorizations:
#   oauth2:
#     grantTypes:
#       authorization_code:
#         tokenEndpoint:
#           - tokenName: auth_code
#           - url: http://petstore.swagger.wordnik.com/oauth/token
#         tokenRequestEndpoint:
#           - url : http://petstore.swagger.wordnik.com/oauth/token
#     implicit:
#       loginEndpoint:
#         url : http://petstore.swagger.wordnik.com/oauth/dialog
securityDefinitions:
  oauth:
    type: oauth2
    flow: implicit
    authorizationUrl: 'https://instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token'
    scopes:
      basic: |
        to read any and all data related to a user (e.g. following/followed-by
         lists, photos, etc.) (granted by default)
paths:
  /ping:
    get:
      security:
       - basicAuth: []
      responses:
        200:
          description: server ping success
        default:
          description: unexpected error
  /jing:
    get:
      operationId: getClusterById
      parameters:
        - name: id
          in: query
          type: string
          required: true
        - name: kd
          in: query
          type: string
          required: true
      responses:
        200:
          description: server ping success
        default:
          description: unexpected error
  /king:
    get:
      security:
       - oauth:
         - basic
      responses:
        200:
          description: server ping success
        default:
          description: unexpected error
