package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetPingOK server ping success

swagger:response getPingOK
*/
type GetPingOK struct {
}

// NewGetPingOK creates GetPingOK with default headers values
func NewGetPingOK() *GetPingOK {
	return &GetPingOK{}
}

// WriteResponse to the client
func (o *GetPingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*GetPingDefault unexpected error

swagger:response getPingDefault
*/
type GetPingDefault struct {
	_statusCode int
}

// NewGetPingDefault creates GetPingDefault with default headers values
func NewGetPingDefault(code int) *GetPingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get ping default response
func (o *GetPingDefault) WithStatusCode(code int) *GetPingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get ping default response
func (o *GetPingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetPingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
