package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetJingOK server ping success

swagger:response getJingOK
*/
type GetJingOK struct {
}

// NewGetJingOK creates GetJingOK with default headers values
func NewGetJingOK() *GetJingOK {
	return &GetJingOK{}
}

// WriteResponse to the client
func (o *GetJingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*GetJingDefault unexpected error

swagger:response getJingDefault
*/
type GetJingDefault struct {
	_statusCode int
}

// NewGetJingDefault creates GetJingDefault with default headers values
func NewGetJingDefault(code int) *GetJingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetJingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get jing default response
func (o *GetJingDefault) WithStatusCode(code int) *GetJingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get jing default response
func (o *GetJingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetJingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
