package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetKingHandlerFunc turns a function with the right signature into a get king handler
type GetKingHandlerFunc func(GetKingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKingHandlerFunc) Handle(params GetKingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetKingHandler interface for that can handle valid get king params
type GetKingHandler interface {
	Handle(GetKingParams, interface{}) middleware.Responder
}

// NewGetKing creates a new http.Handler for the get king operation
func NewGetKing(ctx *middleware.Context, handler GetKingHandler) *GetKing {
	return &GetKing{Context: ctx, Handler: handler}
}

/*GetKing swagger:route GET /king getKing

GetKing get king API

*/
type GetKing struct {
	Context *middleware.Context
	Handler GetKingHandler
}

func (o *GetKing) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetKingParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
