package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetJingHandlerFunc turns a function with the right signature into a get jing handler
type GetJingHandlerFunc func(GetJingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetJingHandlerFunc) Handle(params GetJingParams) middleware.Responder {
	return fn(params)
}

// GetJingHandler interface for that can handle valid get jing params
type GetJingHandler interface {
	Handle(GetJingParams) middleware.Responder
}

// NewGetJing creates a new http.Handler for the get jing operation
func NewGetJing(ctx *middleware.Context, handler GetJingHandler) *GetJing {
	return &GetJing{Context: ctx, Handler: handler}
}

/*GetJing swagger:route GET /jing getJing

GetJing get jing API

*/
type GetJing struct {
	Context *middleware.Context
	Handler GetJingHandler
}

func (o *GetJing) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetJingParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
