package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterByIDParams creates a new GetClusterByIDParams object
// with the default values initialized.
func NewGetClusterByIDParams() GetClusterByIDParams {
	var ()
	return GetClusterByIDParams{}
}

// GetClusterByIDParams contains all the bound params for the get cluster by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getClusterById
type GetClusterByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: query
	*/
	ID string
	/*
	  Required: true
	  In: query
	*/
	Kd string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetClusterByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qID, qhkID, _ := qs.GetOK("id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qKd, qhkKd, _ := qs.GetOK("kd")
	if err := o.bindKd(qKd, qhkKd, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetClusterByIDParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("id", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("id", "query", raw); err != nil {
		return err
	}

	o.ID = raw

	return nil
}

func (o *GetClusterByIDParams) bindKd(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("kd", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("kd", "query", raw); err != nil {
		return err
	}

	o.Kd = raw

	return nil
}
