package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetClusterByIDOK server ping success

swagger:response getClusterByIdOK
*/
type GetClusterByIDOK struct {
}

// NewGetClusterByIDOK creates GetClusterByIDOK with default headers values
func NewGetClusterByIDOK() *GetClusterByIDOK {
	return &GetClusterByIDOK{}
}

// WriteResponse to the client
func (o *GetClusterByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*GetClusterByIDDefault unexpected error

swagger:response getClusterByIdDefault
*/
type GetClusterByIDDefault struct {
	_statusCode int
}

// NewGetClusterByIDDefault creates GetClusterByIDDefault with default headers values
func NewGetClusterByIDDefault(code int) *GetClusterByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetClusterByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get cluster by Id default response
func (o *GetClusterByIDDefault) WithStatusCode(code int) *GetClusterByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get cluster by Id default response
func (o *GetClusterByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetClusterByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
